### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by zayonarts** [LCozzoli/scumHelper#1]
Hi

I am not a python master or something, first time trying to do this, but when i click on the .bat, is not working, after installing all the stuff

I don't understand how to make it work, there is something i am missing...

Add me on discord: Zayon#0157 and i sharescreen you and help me out/explain to me how to do it because i can't make it work.

Thank you

**Comment by LCozzoli** [comment]
Hey, I added you

**Comment by LCozzoli** [comment]
- Added more instructions in the Readme
